### ISSUE TITLE
Add user authentication

### ISSUE THREAD

**Issue by iamdeepti** [iamdeepti/shecure#10]
**Problem**
An unauthentic user might provide false information for feedback, also user authentication will help to personalise the app.

**Solution**
Implement user authentication for the app, can be done by using passport js

**Comment by varunks99** [comment]
@iamdeepti, I would like to work on this.

**Comment by Avn007** [comment]
@iamdeepti Can I work on this issue ?

**Comment by iamdeepti** [comment]
> @iamdeepti, I would like to work on this.

I have assigned the issue to you, go ahead.

**Comment by iamdeepti** [comment]
> @iamdeepti Can I work on this issue ?

Hey @Avn007  maybe you can work on the other one?

**Comment by Avn007** [comment]
> > @iamdeepti Can I work on this issue ?
> 
> Hey @Avn007 maybe you can work on the other one?

Actually I already had a project where I implemented user auth using passport.js and mongodb, so I thought it would be faster, but yeah I understand, I'll try some other issue.
