### ISSUE TITLE
Add travelling duration and distance in the route info panel

### ISSUE THREAD

**Issue by iamdeepti** [iamdeepti/shecure#6]
**Problem** 
Currently, the routes in the app are sorted and colour-coded on the basis of safety score, it's not shown how long it might take the user if he chooses the given route. So the user might select a very long route while trying to pick a safe one.

**Solution**
Display travelling distance and duration for all routes in the panel.

**Comment by maruthimohan** [comment]
Hey @iamdeepti , Could I work on this issue? And btw, your App is really interesting!

**Comment by iamdeepti** [comment]
Thanks, @maruthimohan  I have pointed out an error in your code. Please fix that, and let me know.

**Comment by maruthimohan** [comment]
> Thanks, @maruthimohan I have pointed out an error in your code. Please fix that, and let me know.

Hey @iamdeepti , I have modified the code on the PR. Could you take a look at that? Thank you!
