### ISSUE TITLE
Fix position of search routes button on small screens

### ISSUE THREAD

**Issue by iamdeepti** [iamdeepti/shecure#8]
**Problem**
On mobile or small screens (width <640px) the search routes buttons get hidden behind the destination geocoder.

**Solution**
Can be fixed by adding media query in /client/src/App.css file

**Comment by SahilKumar47** [comment]
I would like to work on it :)

**Comment by SahilKumar47** [comment]
> I would like to work on it :)

assign me pls seniorr
